<?php

if (!defined('_ECRIRE_INC_VERSION')) {
	return;
}

function gs_info_file($user, $repo, $chemin, $reference) {


    // This file is generated by Composer
    require_once __DIR__ . '/vendor/autoload.php';

    $client = new \Github\Client();
    //$repositories = $client->api('user')->repositories('abelass');
    $document = $client->api('repo')->contents()->show($user, $repo, $chemin, $reference);

    $content = base64_decode($document['content']);

	return $content;
}

