<?php

if (!defined('_ECRIRE_INC_VERSION')) {
	return;
}

/**
 * Obtient le contenu d'un document sur github
 *
 * @param string $user
 *  utilisateur github.
 * @param string $repo
 *  le nom du repo github.
 * @param string $chemin
 * 	chemin complet du fichier.
 * @param string $reference
 *  nom de branche ou tag
 *
 * @return string
 */
function gs_contenu_document($user, $repo, $chemin, $reference) {

	// This file is generated by Composer
	require_once __DIR__ . '/vendor/autoload.php';

	$client = new \Redis();
	$client->connect('127.0.0.1', 6379);
	// Create a PSR6 cache pool
	$pool = new RedisCachePool($client);

	$client = new \Github\Client();
	$client->addCache($pool);

	$document = $client->api('repo')->contents()->show($user, $repo, $chemin, $reference);

	$contenu = base64_decode($document['content']);

	return $contenu;
}

